import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from '../components/Hero/Hero'
import HouseCard from '../components/HouseCard/HouseCard'
import MAIN from '../components/Main/Main'


export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
       <Hero/>
        <HouseCard/>
        <MAIN/>
    

  </>
  )
}
